# Generated by Django 2.2 on 2020-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(max_length=1000, verbose_name='محتوا')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
            ],
        ),
    ]
